# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 辽东小码农
email: liaodongxiaoxiao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  写代码是一件很美妙的事情 ^O^     
  Love Coding,Love life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.liaodongxiaoxiao.com" 
twitter_username: Eastern_L
github_username:  liaodongxiaoxiao

# Build settings
markdown: kramdown
